# List of source files for inclusion.
# Order matters — dependencies must be included before their dependents.
include("model/ErrorModule.jl")
include("model/ErrorInfosModule.jl")
include("model/ComparisonModule.jl")
include("model/ConstraintsModule.jl")
include("algorithms/RowEchelonModule.jl")
include("algorithms/SparseRowEchelonModule.jl")
include("model/ConstraintParserModule.jl")
include("io/STANModule.jl")
include("algorithms/ReconciliationModule.jl")
include("algorithms/PresolveModule.jl")
include("algorithms/QCQPModule.jl")
include("solvers/JuMPInterfaceModule.jl")
include("solvers/IpoptSolverModule.jl")
include("solvers/NonlinearSolveInterfaceModule.jl")
include("solvers/DefaultSolverModule.jl")
include("io/SerializationModule.jl")
include("io/ExcelModule.jl")
include("io/HTTPServerModule.jl")
